on:
  push:
    tags:
      - 'v*'
jobs:
  create-executables:
    name: Create Executables
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build JavaScript
        run: npm run build
      - name: Build Executables
        run: npm run dist
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ github.ref_name }}
            release_name: "${{ github.ref_name }}"
      - name: Add Windows Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dist/Disk.gg 1.0.0.exe
          asset_name: Disk-Windows.exe
          asset_content_type: application/octet-stream